name: Build and Deploy dev/stg/prd (Manual)

on:
  workflow_dispatch:
    inputs:
      stage:
        description: 'Deploy stage'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - stg
          - prd

env:
  SERVICE: weatherchart
  AWS_REGION: ap-northeast-1

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # =========================
      # stageごとの設定切替
      # =========================
      - name: Set stage config
        id: stage
        run: |
          STAGE="${{ github.event.inputs.stage }}"
          echo "STAGE=$STAGE" >> $GITHUB_ENV

          if [ "$STAGE" = "prd" ]; then
            echo "ACCOUNT_ID=179698341762" >> $GITHUB_ENV
            echo "DIST_ID=E3W1M78O72OP78" >> $GITHUB_ENV
            echo "VITE_CONTENTS_PATH=https://d3n12iuf4gk58s.cloudfront.net/shared/services/weatherchart/" >> $GITHUB_ENV
          elif [ "$STAGE" = "stg" ]; then
            echo "ACCOUNT_ID=108241940789" >> $GITHUB_ENV
            echo "DIST_ID=E2DYA9BWGLHDV7" >> $GITHUB_ENV
            echo "VITE_CONTENTS_PATH=https://d1xdqsn7je8bay.cloudfront.net/shared/services/weatherchart/" >> $GITHUB_ENV
          else
            echo "ACCOUNT_ID=357665575661" >> $GITHUB_ENV
            echo "DIST_ID=E3KCZCB6BTKPI9" >> $GITHUB_ENV
            echo "VITE_CONTENTS_PATH=https://d34gin1ci1k4s7.cloudfront.net/shared/services/weatherchart/" >> $GITHUB_ENV
          fi

      # =========================
      # AWS認証（OIDC）
      # =========================
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: arn:aws:iam::${{ env.ACCOUNT_ID }}:role/${{ env.SERVICE }}CodeGitHubRole

      # =========================
      # Node セットアップ
      # =========================
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # =========================
      # build（vite）
      # =========================
      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build-${{ env.STAGE }}

      # =========================
      # S3 deploy
      # =========================
      - name: Deploy to S3
        run: |
          aws s3 sync ./dist \
            s3://frontend-${{ env.STAGE }}-${{ env.SERVICE }}-site \
            --delete

      # =========================
      # CloudFront invalidate
      # =========================
      - name: Invalidate CloudFront
        run: |
          aws cloudfront create-invalidation \
            --distribution-id ${{ env.DIST_ID }} \
            --paths "/index.html"

